### ISSUE TITLE
Filter students on coordinator decision status

### ISSUE THREAD

**Issue by mietcls** [opensummerofcode/selections22#3]
Dropdown, should be a multi-select:
<img width="363" alt="Schermafbeelding 2022-06-06 om 15 28 36" src="https://user-images.githubusercontent.com/1572885/172170496-efcc69a9-8135-418a-9f02-ea62be0e6050.png">

Statuses:
<img width="361" alt="Schermafbeelding 2022-06-06 om 15 28 41" src="https://user-images.githubusercontent.com/1572885/172169962-da72a0a9-83e6-4cb3-8f77-dc442d3241d4.png">

**Comment by elroyK** [comment]
Done, deploying rn
